//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class RoomManager
{
	private const int ROOMWIDTH = 8; // 800 px
	private const int ROOMHEIGHT= 6; // 600 px
	private const float ROOMSCALE = 2.0f; // scale of room objects
	private const float TPBUFFER = 0.45f; // translation buffer of movement when teleported

	private GameObject[] rooms;
	private GameObject pc;
	private int currentRoomIndex;
	private float playerSize;

	public RoomManager ()
	{
		// set camera position
		Camera.main.pixelRect = new Rect(0, 0, 800, 600);

		// initialize rooms
		rooms = new GameObject[3];
		initRooms();


		// get player size for calculations
		pc = GameObject.FindGameObjectWithTag("Player");
		playerSize = pc.renderer.bounds.size.x;


		// #DEBUG for testing
		//nextRoom();
	}

	// moves camera & player to next room
	public void nextRoom(){
		Camera.main.transform.position = new Vector3(ROOMWIDTH * ROOMSCALE,0, -10); // move camera to room center
		currentRoomIndex++; // advance room index number
		
		pc.transform.Translate(new Vector3(playerSize + TPBUFFER, pc.transform.position.y + TPBUFFER));

	}// end nextRoom()

	// method adds rooms to game
	private void initRooms(){
		// add rooms to game here, using convention "Room##"
		rooms[0] = GameObject.Find ("Room01");
		rooms[1] = GameObject.Find ("Room02");

		currentRoomIndex = 0;
	}



}// end class


