//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class RoomManager
{
	private const int ROOMWIDTH = 8; // 800 px
	private const int ROOMHEIGHT= 6; // 600 px
	private const float ROOMSCALE = 2.0f; // scale of room objects
	private const float FLOORY = -2.0f; // y-pos of floor (used for playing player in next room)

	private GameObject[] rooms;
	private int currentRoomIndex;
	private float playerSize;

	public RoomManager ()
	{
		// set camera position
		Camera.main.pixelRect = new Rect(0, 0, 800, 600);

		// initialize rooms
		rooms = new GameObject[3];
		initRooms();

		// get player size for calculations
		playerSize = GameObject.FindGameObjectWithTag("Player").renderer.bounds.size.x;

		// #DEBUG for testing
		//nextRoom();
	}

	// moves camera & player to next room
	public void nextRoom(){
		Camera.main.transform.position = new Vector3(ROOMWIDTH * ROOMSCALE,0, -10); // move camera to room center
		currentRoomIndex++; // advance room index number
		GameObject.FindGameObjectWithTag("Player").transform.position = new Vector3(getRoomX(currentRoomIndex) + playerSize, FLOORY); // move player to room start

	}// end nextRoom()

	// method adds rooms to game
	private void initRooms(){
		// add rooms to game here, using convention "Room##"
		rooms[0] = GameObject.Find ("Room01");
		rooms[1] = GameObject.Find ("Room02");

		currentRoomIndex = 0;
	}

	// used to place player at start of room
	private float getRoomX(int roomIndex){ 

		float realHalfWidth = (ROOMWIDTH * ROOMSCALE) / 2; // get half the room width
		return (rooms[roomIndex].transform.position.x - realHalfWidth);
	}


}// end class


